### ISSUE TITLE
does not escape $ 

### ISSUE THREAD

**Issue by zhihengGet** [pawelgrzybek/snippet-generator#92] opened 2023-11-24 03:21 UTC
does not escape $

` import {$isCodeNode} from '@lexical/code';`

"": {
  "prefix": "",
  "body": [
    "import {$isCodeNode} from '@lexical/code';"
  ],
  "description": ""
}

**Comment by pawelgrzybek** [comment] 2023-11-24 17:49
It is a duplicate of #38

**Closed by pawelgrzybek** 2023-11-24 17:49 UTC
